### ISSUE TITLE
Generalize matrix dimensions to enable rectangular matrices

### ISSUE THREAD

**Issue by nicolasbock** [lanl/bml#220]
In order to enable rectangular matrices, the matrix dimension parameters (and the implementation) needs to use two dimensions. For readability, descriptive parameter names should be used:

1. `N_rows`
2. `N_cols`
3. `N_nz_max` (for the ellpack format)

The 2. and 3. parameters should be optional so that existing applications do not break. In particular, `N_cols` should be set to `N_rows` if not given, and `N_nz_max` should be set to `N_rows` if not given.

**Comment by jeanlucf22** [comment]
It looks like the interface to several functions has been changed to include an argument "bml_matrix_dimension_t" instead of one or two integers (N,M). But other functions still use N and M. I am assuming it is because it is still work in progress, right? Can I assume all the arguments will ultimately all be of type "bml_matrix_dimension_t"?
