### ISSUE TITLE
Passthrough arguments for CMake in build script

### ISSUE THREAD

**Issue by awvwgk** [lanl/bml#517]
**Is your feature request related to a problem? Please describe.**
The build shell script only provides a few selected options which are passed to the build script. This makes it difficult to modify the generator (`-G Ninja`) or customize the build beyond the supported environment variables.

**Describe the solution you'd like**
Allow to provide an environment variable or command line option which passes through the `build.sh` script to the CMake command.

**Describe alternatives you've considered**
Directly use CMake to handle the build.

**Additional context**
For example the `-DCMAKE_INSTALL_LIBDIR` argument has to be passed if the `GNUInstallDir` module finds the wrong convention (running conda-build in a CentOS container).

**Comment by nicolasbock** [comment]
Thanks for the suggestion. As you note in lanl/bml#515 adding more flexibility or control to running the `build.sh` script would be helpful.

As a general remark, since the `build.sh` script is really just a convenience layer around `CMake` itself it might be easier if you just call `cmake` directly (as you already note in the _alternatives_ section) in a scenario where you are packaging the `bml`.

I'll certainly have a look at lanl/bml#518.
