### ISSUE TITLE
export BML package for others to use

### ISSUE THREAD

**Issue by jeanlucf22** [lanl/bml#684]
It seems that with BML cmake build system, we are using two different ways of exporting BML and its dependencies for others to use:
1) creating a bml.pc file in the directory where the library is installed (see https://github.com/lanl/bml/blob/0619203a8f63895e0719cb9d293273a5bcef2624/CMakeLists.txt#L737)
2) using cmake "CMakePackageConfigHelpers" (see  https://github.com/lanl/bml/blob/0619203a8f63895e0719cb9d293273a5bcef2624/src/CMakeLists.txt#L103)

Questions: 
(i) shall we focus on only one of these and remove the other one? Is number 2 the better one?
(ii) why is no. 2 in src/CMakeLists.txt instead of the main CMakeLists.txt?

**Comment by jeanlucf22** [comment]
@nicolasbock Any comments on that question?

**Comment by nicolasbock** [comment]
The two solve different issues and my guess is that both are if not necessary but at least helpful at the same time.

1. The first, https://github.com/lanl/bml/blob/0619203a8f63895e0719cb9d293273a5bcef2624/CMakeLists.txt#L737
generates a configuration file for [pkg-config](https://www.freedesktop.org/wiki/Software/pkg-config/) so that it is easier to compile an application with the `bml`. `pkg-config` basically generates the correct compiler flags such as `-L` and `-l`.

4. The second, https://github.com/lanl/bml/blob/0619203a8f63895e0719cb9d293273a5bcef2624/src/CMakeLists.txt#L103 generates a [package configuration file](https://cmake.org/cmake/help/latest/module/CMakePackageConfigHelpers.html) that can be included in another `CMake` based project to create a project consisting of multiple CMake based `packages`.

The second code does not have to be in `src`. I submitted https://github.com/lanl/bml/pull/685 to move it.
