### ISSUE TITLE
Trace test failing for Nvidia offload

### ISSUE THREAD

**Issue by jeanlucf22** [lanl/bml#745]
This function fails on Nvidia:
https://github.com/lanl/bml/blob/e03e7082704b14a703008e318bb4055e60541bd0/src/C-interface/ellpack/bml_trace_ellpack_typed.c#L103

It works on AMD. 

Is it because of the way we split the offload loop into two?
@jmohdyusof @mewall : any comment?

**Comment by mewall** [comment]
Assuming the host arrays for A and B are already allocated with the correct length, the only thing I can see immediately is that rowMin and rowMax need to be shared() instead of A_localRowMin and A_localRowMax. If there are different compilers being used for the host code, this could maybe explain the difference.

BTW I don't see the work being offloaded, the loop is on the host...Or maybe the link was to somewhere else in the code?


________________________________
From: Jean-Luc Fattebert ***@***.***>
Sent: Wednesday, December 6, 2023 6:15 AM
To: lanl/bml ***@***.***>
Cc: Wall, Michael E ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] [lanl/bml] Trace test failing for Nvidia offload (Issue #745)


This function fails on Nvidia:
https://github.com/lanl/bml/blob/e03e7082704b14a703008e318bb4055e60541bd0/src/C-interface/ellpack/bml_trace_ellpack_typed.c#L103<https://urldefense.com/v3/__https://github.com/lanl/bml/blob/e03e7082704b14a703008e318bb4055e60541bd0/src/C-interface/ellpack/bml_trace_ellpack_typed.c*L103__;Iw!!Bt8fGhp8LhKGRg!FFBndPQl1BCRv3TYNOTgI5ennyGu439B34-m02C2eLty5zB22MNczuN37651NNbQkxcjTxyJG1EFfL_Ru_7QRmXb$>

It works on AMD.

Is it because of the way we split the offload loop into two?
@jmohdyusof<https://urldefense.com/v3/__https://github.com/jmohdyusof__;!!Bt8fGhp8LhKGRg!FFBndPQl1BCRv3TYNOTgI5ennyGu439B34-m02C2eLty5zB22MNczuN37651NNbQkxcjTxyJG1EFfL_Ru-EnVGuY$> @mewall<https://urldefense.com/v3/__https://github.com/mewall__;!!Bt8fGhp8LhKGRg!FFBndPQl1BCRv3TYNOTgI5ennyGu439B34-m02C2eLty5zB22MNczuN37651NNbQkxcjTxyJG1EFfL_Ru_ZgCUxX$> : any comment?

**Comment by jeanlucf22** [comment]
Sorry, got the wrong function. Here is the offloaded one:
https://github.com/lanl/bml/blob/e03e7082704b14a703008e318bb4055e60541bd0/src/C-interface/ellpack/bml_trace_ellpack_typed.c#L29

**Comment by mewall** [comment]
Maybe line 52 needs to be

#pragma omp target enter data map(to:rowMax,rowMin,numrows,diag[:numrows])
________________________________
From: Jean-Luc Fattebert ***@***.***>
Sent: Wednesday, December 6, 2023 8:17 AM
To: lanl/bml ***@***.***>
Cc: Wall, Michael E ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [lanl/bml] Trace test failing for Nvidia offload (Issue #745)


Sorry, got the wrong function. Here is the offloaded one:
https://github.com/lanl/bml/blob/e03e7082704b14a703008e318bb4055e60541bd0/src/C-interface/ellpack/bml_trace_ellpack_typed.c#L29<https://urldefense.com/v3/__https://github.com/lanl/bml/blob/e03e7082704b14a703008e318bb4055e60541bd0/src/C-interface/ellpack/bml_trace_ellpack_typed.c*L29__;Iw!!Bt8fGhp8LhKGRg!GcF11oW0mxMHy3NttAKyj0UEOFamswzyRUH7mYEgqz9ESaJHAYbfRep1t-jL2yN0CUP0jwi_7gGimomrxa3iq-c-$>

**Comment by jeanlucf22** [comment]
Was this function ever working and tested for Nvidia?
